import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Check,Plus,RefreshCw,Search,Trash2,X}from'lucide-react';
import{supabase}from'./supabase';

const empty={codice:'',descrizione:'',quantita:'1',riferimento_ordine:'',numero_documento:'',posizione:'',stato:'da_preparare',note:''};
export default function ArticlesManager({onChanged,readOnly=false}){
 const[rows,setRows]=useState([]),[q,setQ]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');const{data,error}=await supabase.from('go_articoli').select('id,codice,descrizione,quantita,riferimento_ordine,numero_documento,posizione,stato,note,created_at').eq('stato','da_preparare');if(error)setError(error.message);else setRows(data||[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')load()};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[load]);
 const orderValue=v=>{const s=String(v??'').trim();const m=s.match(/\d+/);return m?Number(m[0]):Number.POSITIVE_INFINITY};
 const list=useMemo(()=>{const s=q.trim().toLowerCase();const filtered=s?rows.filter(r=>[r.codice,r.descrizione,r.quantita,r.riferimento_ordine,r.numero_documento].some(v=>String(v||'').toLowerCase().includes(s))):rows;return [...filtered].sort((a,b)=>{const d=orderValue(a.numero_documento)-orderValue(b.numero_documento);if(d)return d;return String(a.numero_documento||'').localeCompare(String(b.numero_documento||''),'it',{numeric:true})})},[rows,q]);
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 const edit=r=>{if(readOnly)return;setEditing(r.id);setForm({codice:r.codice||'',descrizione:r.descrizione||'',quantita:r.quantita??'',riferimento_ordine:r.riferimento_ordine||'',numero_documento:r.numero_documento||'',posizione:r.posizione||'',stato:'da_preparare',note:r.note||''});setError('');requestAnimationFrame(()=>document.getElementById(`edit-${r.id}`)?.scrollIntoView({behavior:'smooth',block:'center'}))};
 async function ready(r){if(readOnly)return;if(!window.confirm(`Segnare “${r.descrizione}” come pronto?`))return;setBusy(true);setError('');const{error}=await supabase.from('go_articoli').update({stato:'pronto',updated_at:new Date().toISOString()}).eq('id',r.id);if(error)setError(error.message);else{if(editing===r.id)setEditing(null);await load();await onChanged?.()}setBusy(false)}
 async function save(){if(readOnly)return;const quantita=Number(String(form.quantita).replace(',','.'));if(!form.descrizione.trim())return setError('Inserisci il nome dell’articolo.');if(!Number.isFinite(quantita)||quantita<0)return setError('Inserisci una quantità valida.');setBusy(true);const payload={...form,stato:'da_preparare',codice:form.codice.trim()||null,descrizione:form.descrizione.trim(),quantita,riferimento_ordine:form.riferimento_ordine.trim()||null,numero_documento:form.numero_documento.trim()||null,posizione:form.posizione.trim()||null,note:form.note.trim()||null,updated_at:new Date().toISOString()};const request=editing==='new'?supabase.from('go_articoli').insert(payload):supabase.from('go_articoli').update(payload).eq('id',editing);const{error}=await request;if(error)setError(error.message);else{setEditing(null);await load();await onChanged?.()}setBusy(false)}
 async function remove(r){if(readOnly)return;if(!window.confirm(`Eliminare definitivamente l’articolo “${r.descrizione}”?`))return;setBusy(true);const{error}=await supabase.from('go_articoli').delete().eq('id',r.id);if(error)setError(error.message);else{await load();await onChanged?.()}setBusy(false)}
 const editor=<div className="card articleEditor"><div className="ordersTop"><h3>{editing==='new'?'Nuovo articolo':'Modifica articolo'}</h3><button className="cancelProduct" onClick={()=>setEditing(null)}><X/> Chiudi</button></div><div className="articleFields"><label>Codice<input value={form.codice} onChange={e=>set('codice',e.target.value)}/></label><label>Nome / descrizione<input value={form.descrizione} onChange={e=>set('descrizione',e.target.value)} required/></label><label>Quantità<input type="number" min="0" step="0.001" value={form.quantita} onChange={e=>set('quantita',e.target.value)}/></label><label>Lista<input value={form.riferimento_ordine} onChange={e=>set('riferimento_ordine',e.target.value)}/></label><label>Numero ordine<input value={form.numero_documento} onChange={e=>set('numero_documento',e.target.value)}/></label></div><div className="productActions"><button className="saveProduct" disabled={busy} onClick={save}>{busy?'Salvataggio…':'Salva articolo'}</button><button className="cancelProduct" onClick={()=>setEditing(null)}>Annulla</button></div></div>;
 return <><div className="ordersTop"><div><h2>Articoli da preparare</h2><p>{readOnly?'Visualizzazione in sola lettura.':'Qui compaiono solo gli articoli ancora da preparare.'}</p></div><div className="articleButtons"><button className="refresh" onClick={load}><RefreshCw/>Aggiorna</button>{!readOnly&&<button className="createLoad" onClick={()=>{setEditing('new');setForm(empty);setError('');requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'smooth'}))}}><Plus/>Nuovo articolo</button>}</div></div><div className="searchBox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cerca codice, nome, lista o numero ordine"/></div>{error&&<div className="alert">{error}</div>}{!readOnly&&editing==='new'&&editor}{loading?<div className="card empty">Caricamento articoli…</div>:<div className="orderList">{list.map(r=><React.Fragment key={r.id}><article className="card order"><div className="orderMain"><div className="orderTitle"><strong className="dataCode">{r.codice||'Senza codice'}</strong><span className="status da_preparare">DA PREPARARE</span></div><h3 className="dataName">{r.descrizione}</h3><div className="meta"><span className="dataQty"><b>Q.tà</b> {r.quantita??0}</span><span className="dataList"><b>Lista</b> {r.riferimento_ordine||'—'}</span><span className="dataOrder"><b>Ordine</b> {r.numero_documento||'—'}</span></div></div>{!readOnly&&<div className="articleButtons"><button className="readyBtn" disabled={busy} onClick={()=>ready(r)}><Check/>Pronto</button><button className="editProduct" disabled={busy} onClick={()=>edit(r)}>Modifica</button><button className="deleteArticle" disabled={busy} onClick={()=>remove(r)}><Trash2/>Elimina</button></div>}</article>{!readOnly&&editing===r.id&&<div id={`edit-${r.id}`}>{editor}</div>}</React.Fragment>)}</div>}</>}
