import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Plus,RefreshCw,Search,Trash2,X}from'lucide-react';
import{supabase}from'./supabase';

const empty={codice:'',descrizione:'',quantita:'1',riferimento_ordine:'',numero_documento:'',posizione:'',stato:'da_preparare',note:''};
const states=[['da_preparare','Da preparare'],['pronto','Pronto'],['in_carico','In carico'],['consegnato','Consegnato']];
export default function ArticlesManager({onChanged}){
 const[rows,setRows]=useState([]),[q,setQ]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');const{data,error}=await supabase.from('go_articoli').select('id,codice,descrizione,quantita,riferimento_ordine,numero_documento,posizione,stato,note,created_at').order('created_at',{ascending:false});if(error)setError(error.message);else setRows(data||[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 const list=useMemo(()=>{const s=q.trim().toLowerCase();return s?rows.filter(r=>[r.codice,r.descrizione,r.quantita,r.riferimento_ordine,r.numero_documento,r.posizione,r.stato,r.note].some(v=>String(v||'').toLowerCase().includes(s))):rows},[rows,q]);
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 const edit=r=>{setEditing(r.id);setForm({codice:r.codice||'',descrizione:r.descrizione||'',quantita:r.quantita??'',riferimento_ordine:r.riferimento_ordine||'',numero_documento:r.numero_documento||'',posizione:r.posizione||'',stato:r.stato||'da_preparare',note:r.note||''});setError('')};
 async function save(){const quantita=Number(String(form.quantita).replace(',','.'));if(!form.descrizione.trim())return setError('Inserisci il nome dell’articolo.');if(!Number.isFinite(quantita)||quantita<0)return setError('Inserisci una quantità valida.');setBusy(true);const payload={...form,codice:form.codice.trim()||null,descrizione:form.descrizione.trim(),quantita,riferimento_ordine:form.riferimento_ordine.trim()||null,numero_documento:form.numero_documento.trim()||null,posizione:form.posizione.trim()||null,note:form.note.trim()||null,updated_at:new Date().toISOString()};const request=editing==='new'?supabase.from('go_articoli').insert(payload):supabase.from('go_articoli').update(payload).eq('id',editing);const{error}=await request;if(error)setError(error.message);else{setEditing(null);await load();await onChanged?.()}setBusy(false)}
 async function remove(r){if(!window.confirm(`Eliminare definitivamente l’articolo “${r.descrizione}”?`))return;setBusy(true);const{error}=await supabase.from('go_articoli').delete().eq('id',r.id);if(error)setError(error.message);else{await load();await onChanged?.()}setBusy(false)}
 return <><div className="ordersTop"><div><h2>Gestione articoli</h2><p>Aggiungi, modifica o elimina ogni dettaglio di un articolo.</p></div><div className="articleButtons"><button className="refresh" onClick={load}><RefreshCw/>Aggiorna</button><button className="createLoad" onClick={()=>{setEditing('new');setForm(empty);setError('')}}><Plus/>Nuovo articolo</button></div></div><div className="searchBox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cerca codice, nome, ordine, documento, posizione o lista"/></div>{error&&<div className="alert">{error}</div>}{editing&&<div className="card articleEditor"><div className="ordersTop"><h3>{editing==='new'?'Nuovo articolo':'Modifica articolo'}</h3><button className="cancelProduct" onClick={()=>setEditing(null)}><X/> Chiudi</button></div><div className="articleFields"><label>Codice<input value={form.codice} onChange={e=>set('codice',e.target.value)}/></label><label>Nome / descrizione<input value={form.descrizione} onChange={e=>set('descrizione',e.target.value)} required/></label><label>Quantità<input type="number" min="0" step="0.001" value={form.quantita} onChange={e=>set('quantita',e.target.value)}/></label><label>Numero ordine<input value={form.riferimento_ordine} onChange={e=>set('riferimento_ordine',e.target.value)}/></label><label>Numero documento<input value={form.numero_documento} onChange={e=>set('numero_documento',e.target.value)}/></label><label>Posizione<input value={form.posizione} onChange={e=>set('posizione',e.target.value)}/></label><label>Lista / stato<select value={form.stato} onChange={e=>set('stato',e.target.value)}>{states.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="articleNotes">Note<textarea rows="3" value={form.note} onChange={e=>set('note',e.target.value)}/></label></div><div className="productActions"><button className="saveProduct" disabled={busy} onClick={save}>{busy?'Salvataggio…':'Salva articolo'}</button><button className="cancelProduct" onClick={()=>setEditing(null)}>Annulla</button></div></div>}{loading?<div className="card empty">Caricamento articoli…</div>:<div className="orderList">{list.map(r=><article className="card order" key={r.id}><div className="orderMain"><div className="orderTitle"><strong>{r.codice||'Senza codice'}</strong><span className={'status '+r.stato}>{String(r.stato||'').replaceAll('_',' ')}</span></div><h3>{r.descrizione}</h3><div className="meta"><span><b>Q.tà</b> {r.quantita??0}</span><span><b>Ordine</b> {r.riferimento_ordine||'—'}</span><span><b>Documento</b> {r.numero_documento||'—'}</span><span><b>Posizione</b> {r.posizione||'—'}</span></div>{r.note&&<p>{r.note}</p>}</div><div className="articleButtons"><button className="editProduct" onClick={()=>edit(r)}>Modifica</button><button className="deleteArticle" disabled={busy} onClick={()=>remove(r)}><Trash2/>Elimina</button></div></article>)}</div>}</>}
