import React,{useCallback,useEffect,useState}from'react';
import{CheckCircle2,ChevronDown,ChevronUp,Plus,RefreshCw,Save,Trash2,X,Boxes}from'lucide-react';
import{supabase}from'./supabase';
import'./loads.css';

export default function LoadsV2({onChanged}){
 const[ready,setReady]=useState([]),[loads,setLoads]=useState([]),[selected,setSelected]=useState([]),[open,setOpen]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(null),[qty,setQty]=useState('');
 const palletCount=c=>{const m=String(c.note||'').match(/(\d+)\s+pallet/i);return m?Number(m[1]):(c.go_pallet||[]).length};
 const load=useCallback(async()=>{setError('');const[a,c]=await Promise.all([
  supabase.from('go_articoli').select('id,codice,descrizione,quantita,numero_documento,riferimento_ordine').eq('stato','pronto').order('data_pronto',{ascending:true}),
  supabase.from('go_carichi').select('id,numero,stato,data_carico,data_consegna,note,go_dettagli_carico(id,quantita,codice_snapshot,descrizione_snapshot,articolo_id),go_pallet(id,numero,codice,note)').order('data_consegna',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false})
 ]);if(a.error||c.error)setError((a.error||c.error).message);else{setReady(a.data||[]);setLoads(c.data||[])}},[]);
 useEffect(()=>{load()},[load]);
 const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 async function createLoad(){if(!selected.length)return;setBusy(true);setError('');const number=`C-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-4)}`;const{data:car,error:e1}=await supabase.from('go_carichi').insert({numero:number,stato:'aperto'}).select('id').single();if(e1){setError(e1.message);setBusy(false);return}const chosen=ready.filter(x=>selected.includes(x.id));const{error:e2}=await supabase.from('go_dettagli_carico').insert(chosen.map(x=>({carico_id:car.id,articolo_id:x.id,quantita:x.quantita,codice_snapshot:x.codice,descrizione_snapshot:x.descrizione})));if(e2)setError(e2.message);else{const{error:e3}=await supabase.from('go_articoli').update({stato:'in_carico'}).in('id',selected);if(e3)setError(e3.message)}setSelected([]);await load();await onChanged();setBusy(false)}
 async function saveQty(d){const n=Number(qty);if(!Number.isFinite(n)||n<=0){setError('Inserisci una quantità valida.');return}setBusy(true);const{error}=await supabase.from('go_dettagli_carico').update({quantita:n}).eq('id',d.id);if(error)setError(error.message);else{setEditing(null);setQty('');await load()}setBusy(false)}
 async function removeDetail(d){if(!confirm('Togliere questo articolo dal carico e riportarlo tra i Pronti?'))return;setBusy(true);const{error:e1}=await supabase.from('go_dettagli_carico').delete().eq('id',d.id);if(!e1&&d.articolo_id){const{error:e2}=await supabase.from('go_articoli').update({stato:'pronto',data_pronto:new Date().toISOString()}).eq('id',d.articolo_id);if(e2)setError(e2.message)}else if(e1)setError(e1.message);await load();await onChanged();setBusy(false)}
 async function addPallet(c){setBusy(true);const next=Math.max(0,...(c.go_pallet||[]).map(p=>Number(p.numero)||0))+1;const{error}=await supabase.from('go_pallet').insert({carico_id:c.id,numero:next,codice:`PALLET ${next}`});if(error)setError(error.message);await load();setBusy(false)}
 async function deletePallet(p){if(!confirm(`Eliminare il pallet ${p.numero}?`))return;setBusy(true);const{error}=await supabase.from('go_pallet').delete().eq('id',p.id);if(error)setError(error.message);await load();setBusy(false)}
 async function delivered(c){if(!(c.go_dettagli_carico||[]).length){setError('Il carico non contiene articoli.');return}if(!confirm('Confermi che questo carico è stato consegnato?'))return;setBusy(true);const ids=(c.go_dettagli_carico||[]).map(d=>d.articolo_id).filter(Boolean);const{error:e1}=await supabase.from('go_carichi').update({stato:'consegnato',data_consegna:new Date().toISOString()}).eq('id',c.id);if(!e1&&ids.length){const{error:e2}=await supabase.from('go_articoli').update({stato:'consegnato',data_consegna:new Date().toISOString()}).in('id',ids);if(e2)setError(e2.message)}else if(e1)setError(e1.message);await load();await onChanged();setBusy(false)}
 return <><div className="ordersTop"><div><h2>Gestione carichi</h2><p>Prepara il carico, modifica le quantità e gestisci i pallet.</p></div><button className="refresh" onClick={load}><RefreshCw/> Aggiorna</button></div>{error&&<div className="alert">{error}</div>}
 <div className="loadGrid"><div><h3>Pronti da caricare <span className="badge">{ready.length}</span></h3>{ready.length===0?<div className="card empty">Nessun articolo pronto.</div>:<><div className="readySelect">{ready.map(r=><label className={'card selectRow '+(selected.includes(r.id)?'selected':'')} key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>toggle(r.id)}/><div><strong>{r.codice}</strong><p>{r.descrizione}</p><small>Q.tà {r.quantita} · Doc. {r.numero_documento||'—'} · Ord. {r.riferimento_ordine||'—'}</small></div></label>)}</div><button className="createLoad" disabled={!selected.length||busy} onClick={createLoad}><Plus/> Crea carico con {selected.length} articoli</button></>}</div>
 <div><h3>Carichi</h3>{loads.length===0?<div className="card empty">Nessun carico creato.</div>:<div className="loadList">{loads.map(c=><article className="card loadCard" key={c.id}><button className="loadHead" onClick={()=>setOpen(open===c.id?'':c.id)}><div><strong>{c.numero}</strong><small>{c.data_carico} · {c.stato.toUpperCase()} · {(c.go_dettagli_carico||[]).length} articoli</small></div>{open===c.id?<ChevronUp/>:<ChevronDown/>}</button>{open===c.id&&<div className="loadDetails"><div className="detailTitle"><b>Dettagli carico</b><span>{palletCount(c)} pallet</span></div>{(c.go_dettagli_carico||[]).length===0&&<p className="muted">Nessun articolo nel carico.</p>}{(c.go_dettagli_carico||[]).map(d=><div className="detailRowV2" key={d.id}><div className="detailText"><b>{d.codice_snapshot||'—'}</b><span>{d.descrizione_snapshot||'Articolo'}</span></div>{editing===d.id?<div className="qtyEdit"><input type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(e.target.value)} autoFocus/><button title="Salva" onClick={()=>saveQty(d)} disabled={busy}><Save/></button><button title="Annulla" onClick={()=>setEditing(null)}><X/></button></div>:<div className="detailActions"><button className="qtyBtn" onClick={()=>{setEditing(d.id);setQty(String(d.quantita))}}>Q.tà <b>{d.quantita}</b></button>{c.stato!=='consegnato'&&<button className="iconDanger" title="Togli dal carico" onClick={()=>removeDetail(d)} disabled={busy}><Trash2/></button>}</div>}</div>)}
 {c.stato!=='consegnato'&&<><div className="palletBox"><div className="palletHead"><b><Boxes/> Pallet</b><button onClick={()=>addPallet(c)} disabled={busy}><Plus/> Aggiungi pallet</button></div>{(c.go_pallet||[]).length===0?<small className="muted">Nessun pallet inserito.</small>:<div className="palletList">{[...(c.go_pallet||[])].sort((a,b)=>(a.numero||0)-(b.numero||0)).map(p=><div key={p.id}><span>Pallet <b>{p.numero}</b></span><button title="Elimina pallet" onClick={()=>deletePallet(p)}><Trash2/></button></div>)}</div>}</div><button className="readyBtn deliver" disabled={busy} onClick={()=>delivered(c)}><CheckCircle2/> Segna consegnato</button></>}{c.stato==='consegnato'&&<div className="deliveredMark"><CheckCircle2/> Consegnato</div>}</div>}</article>)}</div>}</div></div></>
}
